{% set name = "prawn-icon" %}
{% set version = "3.0.0" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  - url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
    sha256: dac8d481dee0f60a769c0cab0fd1baec7351b4806bf9ba959cd6c65f6694b6f5

build:
  noarch: generic
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem

requirements:
  host:
    - ruby
  run:
    - {{ pin_compatible('ruby', max_pin='x.x') }}
    - rb-prawn >=1.1.0,<3.0.0

test:
  commands:
    - ruby -r prawn/icon -e 'exit 0'

about:
  home: https://github.com/jessedoyle/prawn-icon
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Prawn::Icon provides various icon fonts including FontAwesome, PaymentFont and Foundation Icons for use with the Prawn PDF toolkit.
  doc_url: https://www.rubydoc.info/gems/prawn-icon
  dev_url: https://github.com/jessedoyle/prawn-icon

extra:
  recipe-maintainers:
    - jdmarques
    - rudispr
